name: Accept GH Invitations Action

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  Execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    # No dependencies needed yet
    - name: Run Script
      run: node app.js --token ${{ secrets.INVITE_ACCESS_TOKEN }}
